image: node:8.11.4

cache:
  paths:
  - node_modules/

stages:
  - test
  
  
before_script:
  - npm install
  - npm build



tests:
  stage: test
  script:
   - npm run test
   
prod_tests:
  stage: test
  script:
   - npm run test-compiled   


#lint:
#  script:
#  - npm run tslint
 
