image: node:8.11.4

cache:
  paths:
  - node_modules/

stages:
  - test
  - build
  
  
before_script:
  - npm install


build_ts:
  stage: build
  script:
    - npm build


tests:
  stage: test
  script:
   - npm run test
   
prod_tests:
  stage: test
  script:
   - npm build && npm run test-compiled   


#lint:
#  script:
#  - npm run tslint
 
