image: node:8.11.4

cache:
  paths:
  - node_modules/

stages:
  - test
  - build
  
  
before_script:
  - npm install

build_ts:
  stage: build
  script:
    - npm build


variables:
  TEST: true
  

run_tests:
  stage: test
  script:
   - npm run test-compiled


#lint:
#  script:
#  - npm run tslint
 
