image: node:8.11.4

cache:
  paths:
  - node_modules/

stages:
  - test
  
  
before_script:
  - npm install
  

tests:
  stage: test
  script:
   - npm run test
   
build_and_tests:
  stage: test
  script:
   - npm run build
   - npm run test-compiled   


#lint:
#  script:
#  - npm run tslint
 
